var zNodes =[
		{ id:'target', pId:0, name:"target", t:"设置触发图相关属性", open:true,
		click:"invoke_target_parent('','target')"},

		{ id:'target_model', pId:'target', name:"model", t:"触发图训练文件的位置,一般为默认,不必修改",
		click:"invoke_target_param('target','model','res/target/model')"},
		{ id:"target_showImmediately", pId:"target", name:"showImmediately", t:"是否需要触发物,true无需触发物立即显示,false需要触发物", 
		click:"invoke_scene_select('target','showImmediately',new Array('true','false'))"},
		{ id:'target_hint', pId:'target', name:"hint", t:"没有跟踪上目标物时的提示文字，如果该字段为空，则使用默认提示文字",
		click:"invoke_target_param('target','hint','对准触发物,稍等片刻。注意调整距离扫描全图')"},
		{ id:'target_tooFarHint', pId:'target', name:"tooFarHint", t:"距离目标物太远的提示文字，如果该字段为空，则使用默认提示",
		click:"invoke_target_param('target','tooFarHint','距离太远！请将镜头靠近')"},
		{ id:'target_tooNearHint', pId:'target', name:"tooNearHint", t:"距离目标物太近的提示文字，如果该字段为空，则使用默认提示",
		click:"invoke_target_param('target','tooNearHint','距离太近！请将镜头远离')"},
		{ id:'target_notFindHint', pId:'target', name:"notFindHint", t:"跟踪不上5s后，出现在屏幕中间的提示文字，不设置时，默认显示：未找到扫描物，请重新对准",
		click:"invoke_target_param('target','notFindHint','未找到扫描物，请重新对准')"},
		{ id:'target_targetName', pId:'target', name:"targetName", t:"目标物名字。用于组合显示在屏幕中的提示文字，当各类xxxhint字段出现时，该字段不起作用。",
		click:"invoke_target_param('target','targetName','name')"},
		{ id:'target_farThreshold', pId:'target', name:"farThreshold", t:"距离目标物过远的阈值",
		click:"invoke_target_param('target','farThreshold','1100')"},
		{ id:'target_nearThreshold', pId:'target', name:"nearThreshold", t:"距离目标物过近的阈值",
		click:"invoke_target_param('target','nearThreshold','600')"},

		{ id:'target_originImage', pId:'target', name:"originImage", t:"触发图的原图",
		click:"invoke_target_parent('target','originImage')"},
		{ id:'originImage_all', pId:'target_originImage', name:"生成所有子节点", t:"",
		click:"invoke_target_param('originImage','sizeWidth','1248'),invoke_target_param('originImage','sizeHeight','734')"},
		{ id:'originImage_sizeWidth', pId:'target_originImage', name:"sizeWidth", t:"宽度",
		click:"invoke_target_param('originImage','sizeWidth','1248')"},
		{ id:'originImage_sizeHeight', pId:'target_originImage', name:"sizeHeight", t:"高度",
		click:"invoke_target_param('originImage','sizeHeight','734')"},

		{ id:'target_featureImage', pId:'target', name:"featureImage", t:"特征图片",
		click:"invoke_target_parent('target','featureImage')"},
		{ id:'featureImage_all', pId:'target_featureImage', name:"生成所有子节点", t:"",
		click:"invoke_target_param('featureImage','sizeWidth','960'),		invoke_target_param('featureImage','sizeHeight','960'),		invoke_target_param('featureImage','resource','res/target/image_target.png'),		invoke_target_param('featureImage','position','480,480,0'),		invoke_target_param('featureImage','targetWidth','414'),		invoke_target_param('featureImage','targetHeight','242')"},
		{ id:'featureImage_sizeWidth', pId:'target_featureImage', name:"sizeWidth", t:"宽度",
		click:"invoke_target_param('featureImage','sizeWidth','960')"},
		{ id:'featureImage_sizeHeight', pId:'target_featureImage', name:"sizeHeight", t:"高度",
		click:"invoke_target_param('featureImage','sizeHeight','960')"},
		{ id:'featureImage_resource', pId:'target_featureImage', name:"resource", t:"特征图片的相对路径",
		click:"invoke_target_param('featureImage','resource','res/target/image_target.png')"},
		{ id:'featureImage_position', pId:'target_featureImage', name:"position", t:"位置",
		click:"invoke_target_param('featureImage','position','480,480,0')"},
		{ id:'featureImage_targetWidth', pId:'target_featureImage', name:"targetWidth", t:"",
		click:"invoke_target_param('featureImage','targetWidth','414')"},
		{ id:'featureImage_targetHeight', pId:'target_featureImage', name:"targetHeight", t:"",
		click:"invoke_target_param('featureImage','targetHeight','242')"},

		{ id:'target_defaultTransform', pId:'target', name:"defaultTransform", t:"跟踪丢失时,模型的各种属性",
		click:"invoke_target_parent('target','defaultTransform')"},
		{ id:'defaultTransform_all', pId:'target_defaultTransform', name:"生成所有子节点", t:"",
		click:"invoke_target_param('defaultTransform','position','-480,-480,654'),		invoke_target_param('defaultTransform','scale','1,1,1'),		invoke_target_param('defaultTransform','rotation','0,0,0')"},
		{ id:'defaultTransform_position', pId:'target_defaultTransform', name:"position", t:"位置",
		click:"invoke_target_param('defaultTransform','position','-480,-480,654')"},
		{ id:'defaultTransform_scale', pId:'target_defaultTransform', name:"scale", t:"大小",
		click:"invoke_target_param('defaultTransform','scale','1,1,1')"},
		{ id:'defaultTransform_rotation', pId:'target_defaultTransform', name:"rotation", t:"角度",
		click:"invoke_target_param('defaultTransform','rotation','0,0,0')"},

		{ id:"sceneList", pId:0, name:"sceneList", t:"场景列表", open:true,
		click:"invoke_target_list('','sceneList')"},
		{ id:"sceneList_item", pId:"sceneList", name:"sceneListItem", t:"Item,请务必点击该节点用来包裹之后的属性元素", open:true,
		click:"invoke_listitem_warpper('sceneList','sceneListitem')"},
		{ id:"sceneList_item_name", pId:"sceneList_item", name:"name", t:"该case的名字,英文", open:true,
		click:"invoke_scene_param('sceneListitem','name','case_name')"},
		{ id:"sceneList_item_zNear", pId:"sceneList_item", name:"zNear", t:"距离目标物的最近位置,非必选", open:true,
		click:"invoke_scene_param('sceneListitem','zNear','50')"},
		{ id:"sceneList_item_zNear", pId:"sceneList_item", name:"zNear", t:"距离目标物的最近位置,非必选", open:true,
		click:"invoke_scene_param('sceneListitem','zNear','50')"},
		{ id:"objList", pId:"sceneList_item", name:"objList", t:"模型对象列表", open:true,
		click:"invoke_target_list('sceneListitem','objList')"},
		{ id:"objList_item", pId:"objList", name:"objListItem", t:"Item,请务必点击该节点用来包裹之后的属性元素", open:true,
		click:"invoke_listitem_warpper('objList','objListItem')"},
		{ id:"objList_item_comment", pId:"objList_item", name:"comment", t:"该模型的名称,推荐中文", 
		click:"invoke_scene_param('objListItem','comment','名字')"},
		{ id:"objList_item_id", pId:"objList_item", name:"id", t:"该模型的ID,推荐英文", 
		click:"invoke_scene_param('objListItem','id','')"},
		{ id:"objList_item_type", pId:"objList_item", name:"type", t:"该模型的类型,obj和objser选择static,md2选择dynamic,图片选择plane", 
		click:"invoke_scene_select('objListItem','type',new Array('static','dynamic','plane'))"},
		{ id:"objList_item_priority", pId:"objList_item", name:"priority", t:"分步加载优先级,范围0-200", 
		click:"invoke_scene_param('objListItem','priority','0')"},
		{ id:"objList_item_positionScreen", pId:"objList_item", name:"positionScreen", t:"x、y使用屏占比表示。只有camera类型为camera_3d_ui时，positionScreen字段才会代替position字段表示模型位置", 
		click:"invoke_scene_param('objListItem','positionScreen','0.2,0.33,100.0')"},
		{ id:"objList_item_cameraId", pId:"objList_item", name:"cameraId", t:"相机ID", 
		click:"invoke_scene_param('objListItem','cameraId','id001')"},
		{ id:"objList_item_cameraType", pId:"objList_item", name:"cameraType", t:"相机类型.包括camera_2d_ui(2D随屏UI相机),camera_target_fix(3D随目标物相机),camera_3d_ui,camera_3D_target_moveable。目前我们用到的是前两种。", 
		click:"invoke_scene_select('objListItem','cameraType',new Array('camera_2d_ui','camera_target_fix','camera_3d_ui','camera_3D_target_moveable'))"},
		{ id:'objList_item_planePosition', pId:'objList_item', name:"planePosition", t:"2D 随屏目标物在屏幕的位置",
		click:"invoke_target_parent('objListItem','planePosition')"},
			{ id:'planePosition_widthAndHeight', pId:'objList_item_planePosition', name:"widthAndHeight", t:"目标物宽高",
			click:"invoke_target_param('planePosition','widthAndHeight','300,200')"},
			{ id:'planePosition_percent', pId:'objList_item_planePosition', name:"percent", t:"目标物屏占比",
			click:"invoke_target_param('planePosition','percent','50')"},
			{ id:"planePosition_normalizeWidth", pId:"objList_item_planePosition", name:"normalizeWidth", t:"以屏幕宽度计算目标物屏占比.", 
			click:"invoke_scene_select('planePosition','normalizeWidth',new Array('true','false'))"},
			{ id:"planePosition_normalizeHeight", pId:"objList_item_planePosition", name:"normalizeHeight", t:"以屏幕高度计算目标物屏占比.", 
			click:"invoke_scene_select('planePosition','normalizeHeight',new Array('true','false'))"},
			{ id:"planePosition_screenOritation", pId:"objList_item_planePosition", name:"screenOritation", t:"屏幕方向.true 表示横屏,false 表示竖屏.", 
			click:"invoke_scene_select('planePosition','screenOritation',new Array('true','false'))"},
			{ id:"planePosition_alignParentLeft", pId:"objList_item_planePosition", name:"alignParentLeft", t:"居左.", 
			click:"invoke_scene_select('planePosition','alignParentLeft',new Array('true','false'))"},
			{ id:"planePosition_alignParentRight", pId:"objList_item_planePosition", name:"alignParentRight", t:"居右.", 
			click:"invoke_scene_select('planePosition','alignParentRight',new Array('true','false'))"},
			{ id:"planePosition_alignParentTop", pId:"objList_item_planePosition", name:"alignParentTop", t:"居于顶部.", 
			click:"invoke_scene_select('planePosition','alignParentTop',new Array('true','false'))"},
			{ id:"planePosition_alignParentBottom", pId:"objList_item_planePosition", name:"alignParentBottom", t:"居于底部.", 
			click:"invoke_scene_select('planePosition','alignParentBottom',new Array('true','false'))"},
			{ id:"planePosition_centerVertical", pId:"objList_item_planePosition", name:"centerVertical", t:"垂直居中.", 
			click:"invoke_scene_select('planePosition','centerVertical',new Array('true','false'))"},
			{ id:"planePosition_centerHorizontal", pId:"objList_item_planePosition", name:"centerHorizontal", t:"水平居中.", 
			click:"invoke_scene_select('planePosition','centerHorizontal',new Array('true','false'))"},
			{ id:'planePosition_marginLeft', pId:'objList_item_planePosition', name:"marginLeft", t:"左边距",
			click:"invoke_target_param('planePosition','marginLeft','0')"},
			{ id:'planePosition_marginRight', pId:'objList_item_planePosition', name:"marginRight", t:"右边距",
			click:"invoke_target_param('planePosition','marginRight','0')"},
			{ id:'planePosition_marginTop', pId:'objList_item_planePosition', name:"marginTop", t:"上边距",
			click:"invoke_target_param('planePosition','marginTop','0')"},
			{ id:'planePosition_marginBottom', pId:'objList_item_planePosition', name:"marginBottom", t:"下边距",
			click:"invoke_target_param('planePosition','marginBottom','0')"},
		{ id:"objList_item_position", pId:"objList_item", name:"position", t:"模型位置", 
		click:"invoke_scene_param('objListItem','position','0.0,0.0,0.0')"},
		{ id:"objList_item_scale", pId:"objList_item", name:"scale", t:"模型大小", 
		click:"invoke_scene_param('objListItem','scale','1.0,1.0,1.0')"},
		{ id:"objList_item_rotation", pId:"objList_item", name:"rotation", t:"模型角度", 
		click:"invoke_scene_param('objListItem','rotation','180.0,1.0,1.0')"},
		{ id:"objList_item_isNeedDownSample", pId:"objList_item", name:"isNeedDownSample", t:"增强模型清晰度,false为增强,true为不增强", 
		click:"invoke_scene_select('objListItem','isNeedDownSample',new Array('false','true'))"},
		{ id:"objList_item_visible", pId:"objList_item", name:"visible", t:"设置模型的可见状态,1为可见,0为不可见", 
		click:"invoke_scene_select('objListItem','visible',new Array('1','0'))"},
		{ id:'objList_item_texture', pId:'objList_item', name:"texture", t:"2D随屏目标物",
		click:"invoke_target_parent('objListItem','texture')"},
			{ id:"texture_type", pId:"objList_item_texture", name:"type", t:"类型", 
			click:"invoke_scene_select('texture','type',new Array('image'))"},
			{ id:"texture_startMode", pId:"objList_item_texture", name:"startMode", t:"auto启动模式时，为默认在视频前面再加一段视频，前提是该视频存在，路径为res/video/prefix.mp4", 
			click:"invoke_scene_select('texture','startMode',new Array('auto','trigger'))"},
			{ id:"texture_playType", pId:"objList_item_texture", name:"playType", t:"单播或者循环", 
			click:"invoke_scene_select('texture','playType',new Array('single','repeat'))"},
			{ id:"texture_imageList", pId:"objList_item_texture", name:"imageList", t:'图片列表,直接在[]中添加图片名称,以逗号分隔,例如["1.jpg","2.jpg"]',
			click:"invoke_target_list('texture','imageList')"},
			{ id:"texture_videoList", pId:"objList_item_texture", name:"videoList", t:'视频列表',
			click:"invoke_target_list('texture','videoList')"},
				{ id:"texture_videoList_item", pId:"texture_videoList", name:"videoListItem", t:"Item,请务必点击该节点用来包裹videoList的属性元素", 
				click:"invoke_listitem_warpper('videoList','videoListItem')"},
					{ id:"texture_imageList_resource", pId:"texture_videoList_item", name:"resource", t:"模型角度", 
					click:"invoke_scene_param('videoListItem','resource','res/Glory_Of_Nature.mp4')"},
					{ id:"texture_imageList_playType", pId:"texture_videoList_item", name:"playType", t:"单播或者循环", 
					click:"invoke_scene_select('videoListItem','playType',new Array('single','repeat'))"},
		{ id:"objList_item_sizeX", pId:"objList_item", name:"sizeX", t:"在X轴方向的长度", 
		click:"invoke_scene_param('objListItem','sizeX','100')"},
		{ id:"objList_item_sizeY", pId:"objList_item", name:"sizeY", t:"在Y轴方向的长度", 
		click:"invoke_scene_param('objListItem','sizeY','100')"},

		{ id:"lights_list", pId:"objList_item", name:"lights", t:"灯光",
		click:"invoke_target_list('objListItem','lights')"},
		{ id:"lights_template", pId:"lights_list", name:"使用lights模板", t:"", 
		click:"useLightsTemplate()"},
		{ id:"lights_list_item", pId:"lights_list", name:"lightsItem", t:"Item,请务必点击该节点用来包裹lights的属性元素", 
		click:"invoke_listitem_warpper('lights','lightsItem')"},
			{ id:"lights_item_type", pId:"lights_list_item", name:"type", t:"灯光类型", 
			click:"invoke_scene_select('lightsItem','type',new Array('directional'))"},
			{ id:"lights_item_direction", pId:"lights_list_item", name:"direction", t:"灯光方向", 
			click:"invoke_scene_param('lightsItem','direction','1, 0, 0')"},
			{ id:"lights_item_power", pId:"lights_list_item", name:"power", t:"灯光强度", 
			click:"invoke_scene_param('lightsItem','power','0.5')"},

		{ id:'attribute', pId:'objList_item', name:"attribute", t:"特殊属性,一般情况下无需设置",
		click:"invoke_target_parent('objListItem','attribute')"},
		{ id:"attribute_sided", pId:"attribute", name:"sided", t:"设置透明的面", 
		click:"invoke_scene_select('attribute','sided',new Array('single'))"},
		{ id:"attribute_transparent", pId:"attribute", name:"transparent", t:"透明", 
		click:"invoke_scene_select('attribute','transparent',new Array('true','false'))"},

		{ id:'staticRes', pId:'objList_item', name:"staticRes", t:"静态资源,obj和objser模型请选择该项",
		click:"invoke_target_parent('objListItem','staticRes')"},
		{ id:"staticRes_type", pId:"staticRes", name:"type", t:"类型", 
		click:"invoke_scene_select('staticRes','type',new Array('objser','obj'))"},
		{ id:"staticRes_resource", pId:"staticRes", name:"resource", t:"相对路径", 
		click:"invoke_scene_param('staticRes','resource','res/model/filename.objser')"},

		{ id:'dynamicRes', pId:'objList_item', name:"dynamicRes", t:"动态资源,md2模型请选择该项",
		click:"invoke_target_parent('objListItem','dynamicRes')"},
		{ id:"dynamicRes_type", pId:"dynamicRes", name:"type", t:"类型", 
		click:"invoke_scene_select('dynamicRes','type',new Array('md2'))"},
		{ id:"dynamicRes_resource", pId:"dynamicRes", name:"resource", t:"相对路径", 
		click:"invoke_scene_param('dynamicRes','resource','res/model/filename.md2')"},

		{ id:"instructions_list", pId:"objList_item", name:"instructions", t:"指令集",
		click:"invoke_target_list('objListItem','instructions')"},
			{ id:"instructions_list_item", pId:"instructions_list", name:"instructionsItem", t:"Item,请务必点击该节点用来包裹instructions的属性元素", open:true,click:"invoke_listitem_warpper('instructions','instructionsItem')"},
				{ id:"instructions_target", pId:"instructions_list_item", name:"target", t:"执行指令的目标", 
				click:"invoke_scene_param('instructionsItem','target','target name')"},
				{ id:"instructions_forwardLogic", pId:"instructions_list_item", name:"forwardLogic", t:"前向逻辑", 
				click:"invoke_scene_select('instructionsItem','forwardLogic',new Array('CancleForward','ForceCancleForward','WaitForward'))"},
				{ id:"instructions_backwardLogic", pId:"instructions_list_item", name:"backwardLogic", t:"后向逻辑",
				click:"invoke_scene_select('instructionsItem','backwardLogic',new Array('CanBeCancled','CanNotBeCancled','CancleBackward'))"},
				{ id:"instructions_instructType", pId:"instructions_list_item", name:"instructType", t:"指令类型",
				click:"invoke_scene_select('instructionsItem','instructType',new Array('InstructionSet'))"},
				{ id:"instructions_instructCategory", pId:"instructions_list_item", name:"instructCategory", t:"指令策略",
				click:"invoke_scene_select('instructionsItem','instructCategory',new Array('StartInstructSet','ClickInstructSet','TrackFoundInstructSet','TrackLostInstructSet'))"},
				{ id:"instructions_instructId", pId:"instructions_list_item", name:"instructId", t:"指令ID", 
				click:"invoke_scene_param('instructionsItem','instructId','id')"},
				{ id:"instructions_param_list", pId:"instructions_list_item", name:"param", t:"指令参数列表", open:true,
				click:"invoke_target_list('instructionsItem','param')"},
				{ id:"instructions_param_list_item", pId:"instructions_param_list", name:"paramItem",
				 t:"Item,请务必点击该节点用来包裹param的属性元素",click:"invoke_listitem_warpper('param','paramItem')"},
					{ id:"paramlist_target", pId:"instructions_param_list_item", name:"target", t:"执行指令的目标", 
					click:"invoke_scene_param('paramItem','target','target name')"},
					{ id:"paramlist_forwardLogic", pId:"instructions_param_list_item", name:"forwardLogic", t:"前向逻辑", 
					click:"invoke_scene_select('paramItem','forwardLogic',new Array('CancleForward','ForceCancleForward','WaitForward'))"},
					{ id:"paramlist_backwardLogic", pId:"instructions_param_list_item", name:"backwardLogic", t:"后向逻辑",
					click:"invoke_scene_select('paramItem','backwardLogic',new Array('CanBeCancled','CanNotBeCancled','CancleBackward'))"},
					{ id:"paramlist_instructType", pId:"instructions_param_list_item", name:"instructType", t:"指令类型",
					click:"invoke_scene_select('paramItem','instructType',new Array('AtomInstruction','InstructionSet'))"},
					{ id:"paramlist_instructCategory", pId:"instructions_param_list_item", name:"instructCategory", t:"指令策略",
					click:"invoke_scene_select('paramItem','instructCategory',new Array('PlayMusicInstruct','PlayMd2AnimInstruct','ChangeSceneInstruct','ChangePlayStatusInstruct','MuteInstruct','AnimationInstruct','ChangePropertyInstruct','translateScreen3D','PlayMatrixAnimationInstruct'))"},
					{ id:"paramlist_instructId", pId:"instructions_param_list_item", name:"instructId", t:"指令ID", 
					click:"invoke_scene_param('paramItem','instructId','id')"},
					{ id:'paramlist_param', pId:'instructions_param_list_item', name:"param", t:"指令参数",
					click:"invoke_target_parent('paramItem','param_')"},
												
							{ id:"param_type", pId:"paramlist_param", name:"type", t:"类型", 
							click:"invoke_scene_select('param_','type',new Array('posture','postureScreen3D','change_position_screen','video','matrix'))"},
							{ id:"param_matrixName", pId:"paramlist_param", name:"matrixName", t:"矩阵名称", 
							click:"invoke_scene_param('param_','matrixName','matrix.mat')"},
							{ id:"param_action", pId:"paramlist_param", name:"action", t:"动作", 
							click:"invoke_scene_select('param_','action',new Array('start','pause','restart','reverse'))"},
							{ id:"param_changeType", pId:"paramlist_param", name:"changeType", t:"改变类型", 
							click:"invoke_scene_select('param_','changeType',new Array('absolute','increase','limit_increase','rnd_increase','rnd_limit_increase'))"},
							{ id:"param_toValue", pId:"paramlist_param", name:"toValue", t:"x、y值使用屏占比表示，范围0-1时出现在手机屏幕上，z是三维空间绝对值", 
							click:"invoke_scene_param('param_','toValue','0.2,0.33,100.0')"},
							{ id:"param_limitLow", pId:"paramlist_param", name:"limitLow", t:"x、y使用屏占比表示，z是三维空间绝对值", 
							click:"invoke_scene_param('param_','limitLow','0.1,0.2,100.0')"},
							{ id:"param_limitHigh", pId:"paramlist_param", name:"limitHigh", t:"x、y使用屏占比表示，z是三维空间绝对值", 
							click:"invoke_scene_param('param_','limitHigh','0.4,0.5,100.0')"},
							{ id:"param_duration", pId:"paramlist_param", name:"duration", t:"时长", 
							click:"invoke_scene_param('param_','duration','1000')"},
							{ id:"param_length", pId:"paramlist_param", name:"length", t:"有效时长", 
							click:"invoke_scene_param('param_','length','1000')"},
							{ id:"param_start", pId:"paramlist_param", name:"start", t:"开始时间", 
							click:"invoke_scene_param('param_','start','0')"},
							{ id:"param_delay", pId:"paramlist_param", name:"delay", t:"延迟时间", 
							click:"invoke_scene_param('param_','delay','0')"},
							{ id:"param_updateRate", pId:"paramlist_param", name:"updateRate", t:"更新频率", 
							click:"invoke_scene_param('param_','updateRate','10')"},
							{ id:"param_direction", pId:"paramlist_param", name:"direction", t:"方向", 
							click:"invoke_scene_param('param_','direction','1')"},
							{ id:'param_interpolator', pId:'paramlist_param', name:"interpolator", t:"插值器",click:"invoke_target_parent('param_','interpolator')"},
								{ id:"interpolator_type", pId:"param_interpolator", name:"type", t:"类型", click:"invoke_scene_select('interpolator','type',new Array('Linear'))"},
							{ id:'param_fromPosition', pId:'paramlist_param', name:"fromPosition", t:"起始位置",click:"invoke_target_parent('param_','fromPosition')"},
								{ id:"fromPosition_", pId:"param_fromPosition", name:"null", t:"", 
								click:""},
							{ id:'param_toPosition', pId:'paramlist_param', name:"toPosition", t:"终止位置",click:"invoke_target_parent('param_','toPosition')"},
								{ id:"toPosition_type", pId:"param_toPosition", name:"animDataType", t:"坐标类型", click:"invoke_scene_select('toPosition','animDataType',new Array('absolute'))"},
								{ id:"toPosition_absoluteNum", pId:"param_toPosition", name:"absoluteNum", t:"位置坐标", 
								click:"invoke_scene_param('toPosition','absoluteNum','0.0,0.0,0.0')"},
							{ id:'param_fromScale', pId:'paramlist_param', name:"fromScale", t:"起始大小",click:"invoke_target_parent('param_','fromScale')"},
								{ id:"fromScale_type", pId:"param_fromScale", name:"animDataType", t:"数据类型", click:"invoke_scene_select('fromScale','animDataType',new Array('absolute'))"},
								{ id:"fromScale_absoluteNum", pId:"param_fromScale", name:"absoluteNum", t:"值", 
								click:"invoke_scene_param('fromScale','absoluteNum','1,1,1')"},
							{ id:'param_toScale', pId:'paramlist_param', name:"toScale", t:"终止大小",click:"invoke_target_parent('param_','toScale')"},
								{ id:"toScale_type", pId:"param_toScale", name:"animDataType", t:"数据类型", click:"invoke_scene_select('toScale','animDataType',new Array('absolute'))"},
								{ id:"toScale_absoluteNum", pId:"param_toScale", name:"absoluteNum", t:"值", 
								click:"invoke_scene_param('toScale','absoluteNum','1,1,1')"},
							{ id:'param_fromRotate', pId:'paramlist_param', name:"fromRotate", t:"起始角度",click:"invoke_target_parent('param_','fromRotate')"},
								{ id:"fromRotate_type", pId:"param_fromRotate", name:"animDataType", t:"数据类型", click:"invoke_scene_select('fromRotate','animDataType',new Array('absolute'))"},
								{ id:"fromRotate_absoluteNum", pId:"param_fromRotate", name:"absoluteNum", t:"角度值", 
								click:"invoke_scene_param('fromRotate','absoluteNum','180,-180,0')"},
							{ id:'param_toRotate', pId:'paramlist_param', name:"toRotate", t:"终止角度",click:"invoke_target_parent('param_','toRotate')"},
								{ id:"toRotate_type", pId:"param_toRotate", name:"animDataType", t:"数据类型", click:"invoke_scene_select('toRotate','animDataType',new Array('absolute'))"},
								{ id:"toRotate_absoluteNum", pId:"param_toRotate", name:"absoluteNum", t:"角度值", 
								click:"invoke_scene_param('toRotate','absoluteNum','180,-180,0')"},
							{ id:'param_fromPositionScreen3D', pId:'paramlist_param', name:"fromPositionScreen3D", t:"起始位置",
							click:"invoke_target_parent('param_','fromPositionScreen3D')"},
								{ id:"fromPositionScreen3D_animDataType", pId:"param_fromPositionScreen3D", name:"animDataType", t:"动画数据类型", 
								click:"invoke_scene_select('fromPositionScreen3D','animDataType',new Array('absolute','absolute_limit','increase','increase_limit'))"},
								{ id:"fromPositionScreen3D_absoluteNum", pId:"param_fromPositionScreen3D", name:"absoluteNum", t:"绝对数值", 
								click:"invoke_scene_param('fromPositionScreen3D','absoluteNum','0.2,0.33,100.0')"},
								{ id:"fromPositionScreen3D_limitNum", pId:"param_fromPositionScreen3D", name:"limitNum", t:"范围", 
								click:"invoke_scene_param('fromPositionScreen3D','limitNum','0.2,0.33,100.0: 0.4,0.5,100.0')"},
							{ id:'param_toPositionScreen3D', pId:'paramlist_param', name:"toPositionScreen3D", t:"终止位置",
							click:"invoke_target_parent('param_','toPositionScreen3D')"},
								{ id:"toPositionScreen3D_animDataType", pId:"param_toPositionScreen3D", name:"animDataType", t:"动画数据类型", 
								click:"invoke_scene_select('toPositionScreen3D','animDataType',new Array('absolute','absolute_limit','increase','increase_limit'))"},
								{ id:"toPositionScreen3D_absoluteNum", pId:"param_toPositionScreen3D", name:"absoluteNum", t:"绝对数值", 
								click:"invoke_scene_param('toPositionScreen3D','absoluteNum','0.2,0.33,100.0')"},
								{ id:"toPositionScreen3D_limitNum", pId:"param_toPositionScreen3D", name:"limitNum", t:"范围", 
								click:"invoke_scene_param('toPositionScreen3D','limitNum','0.2,0.33,100.0: 0.4,0.5,100.0')"},


						
							{ id:"param_resPath", pId:"paramlist_param", name:"resPath", t:"相对路径", 
								click:"invoke_scene_param('param_','resPath','res/filename.mp3')"},

						
							{ id:"param_playType", pId:"paramlist_param", name:"playType", t:"播放类型", 
								click:"invoke_scene_select('param_','playType',new Array('repeat'))"},
							{ id:"param_md2AnimName", pId:"paramlist_param", name:"md2AnimName", t:"动画名称,可不填", 
							click:"invoke_scene_param('param_','md2AnimName','')"},

							{ id:"param_sceneId", pId:"paramlist_param", name:"sceneId", t:"场景ID", 
							click:"invoke_scene_param('param_','md2AnimName','')"},

							{ id:"param_type", pId:"paramlist_param", name:"type", t:"类型", 
								click:"invoke_scene_select('param_','type',new Array('change_visible','change_clickable'))"},
							{ id:"param_visibleType", pId:"paramlist_param", name:"visibleType", t:"可见状态", 
								click:"invoke_scene_select('param_','visibleType',new Array('visible','invisible'))"},
							{ id:"param_clickableType", pId:"paramlist_param", name:"clickableType", t:"可点击类型,clickable为可点击,unclickable为不可点击,switch为切换可点击状态,none为无", 
								click:"invoke_scene_select('param_','clickableType',new Array('clickable','unclickable','switch','none'))"},
						    
						    { id:"param_mute", pId:"paramlist_param", name:"mute", t:"静音", 
								click:"invoke_scene_select('param_','mute',new Array('true','false'))"},



		{ id:"instructions_param_list_item_gesture", pId:"instructions_param_list", name:"paramItem姿态调整模板", t:"实现模型的姿态调整,包括位置,大小,角度",click:"invoke_posture_all()"},
		{ id:"instructions_param_list_item_position", pId:"instructions_param_list", name:"paramItem位置调整模板", t:"实现模型的位置调整",click:"invoke_position_all()"},
		{ id:"instructions_param_list_item_scale", pId:"instructions_param_list", name:"paramItem大小调整模板", t:"实现模型的大小调整",click:"invoke_scale_all()"},
		{ id:"instructions_param_list_item_rotation", pId:"instructions_param_list", name:"paramItem角度调整模板", t:"实现模型的角度调整",click:"invoke_rotation_all()"},
		{ id:"instructions_param_list_item_bgm", pId:"instructions_param_list", name:"paramItem背景音乐模板", t:"添加背景音乐",click:"invoke_bgm_all()"},
		{ id:"instructions_param_list_item_playAnimation", pId:"instructions_param_list", name:"paramItem播放动画模板", t:"播放动画",click:"invoke_playAnimation_all()"},
		// { id:"instructions_param_list_item_changeScene", pId:"instructions_param_list", name:"paramItem场景切换", t:"场景切换",click:"invoke_changeScene_all()"},
		{ id:"instructions_param_list_item_changeVisible", pId:"instructions_param_list", name:"paramItem可见状态切换模板", t:"可见状态切换",click:"invoke_changeVisible_all()"},
		{ id:"instructions_param_list_item_change_clickable", pId:"instructions_param_list", name:"paramItem可点击状态切换模板", t:"可点击状态切换",click:"invoke_change_clickable_all()"},
		
		{ id:"instructions_param_list_item_change_playstatus", pId:"instructions_param_list", name:"paramItem改变视频播放状态的指令模板", t:"改变视频播放状态的指令",click:"invoke_change_playstatus_all()"},

		{ id:"instructions_param_list_item_mute", pId:"instructions_param_list", name:"paramItem可静音模板", t:"静音状态切换",click:"invoke_mute_all()"},
		{ id:"instructions_param_list_item_change_position_screen", pId:"instructions_param_list", name:"paramItem三维随屏模型的改变position属性的指令模板", t:"三维随屏模型的改变position属性的指令",click:"invoke_change_position_screen_all()"},



		{ id:"sceneList_instructions_list", pId:"sceneList_item", name:"instructions", t:"指令集",
		click:"invoke_target_list('sceneListitem','instructions')"},
			{ id:"sceneList_instructions_list_item", pId:"sceneList_instructions_list", name:"instructionsItem", t:"Item,请务必点击该节点用来包裹instructions的属性元素", open:true,
			click:"invoke_listitem_warpper('instructions','instructionsItem')"},
				{ id:"sceneList_instructions_target", pId:"sceneList_instructions_list_item", name:"target", t:"执行指令的目标", 
				click:"invoke_scene_param('instructionsItem','target','target name')"},
				{ id:"sceneList_instructions_forwardLogic", pId:"sceneList_instructions_list_item", name:"forwardLogic", t:"前向逻辑", 
				click:"invoke_scene_select('instructionsItem','forwardLogic',new Array('WaitForward','ForceCancleForward','WaitForward'))"},
				{ id:"sceneList_instructions_backwardLogic", pId:"sceneList_instructions_list_item", name:"backwardLogic", t:"后向逻辑",
				click:"invoke_scene_select('instructionsItem','backwardLogic',new Array('CanBeCancled','CanNotBeCancled','CancleBackward'))"},
				{ id:"sceneList_instructions_instructType", pId:"sceneList_instructions_list_item", name:"instructType", t:"指令类型",
				click:"invoke_scene_select('instructionsItem','instructType',new Array('InstructionSet'))"},
				{ id:"sceneList_instructions_instructCategory", pId:"sceneList_instructions_list_item", name:"instructCategory", t:"指令策略",
				click:"invoke_scene_select('instructionsItem','instructCategory',new Array('TrackFoundInstructSet','TrackLostInstructSet'))"},
				{ id:"sceneList_instructions_instructId", pId:"sceneList_instructions_list_item", name:"instructId", t:"指令ID", 
				click:"invoke_scene_param('instructionsItem','instructId','id')"},
				{ id:"sceneList_instructions_param_list", pId:"sceneList_instructions_list_item", name:"param", t:"指令参数列表", open:true,
				click:"invoke_target_list('instructionsItem','param')"},
		];